### PR TITLE
Backend Dev into Main

### PR DESCRIPTION
**Pull request by DonoghueRyan**
Route name changes, a couple of new routes, start of error checking

### CODE REVIEW

**Comment by DonoghueRyan** [comment]
[Merge Request #20.pdf](https://github.com/vivjamba/goals-for-gordon/files/9966881/Merge.Request.20.pdf)

**Comment by ChrisWeldon** [comment]
Ready to go. 

**Important**: I moved .env to root of server goals-for-gordon/server. I did this because dotenv simulates the environment and is not directory specific. Having env files deep in a directory will still hydrate the environment globally which is confusing for devs, not to mention that the environment gets hydrated differently depending on what build is being used.

**Comment by SiCh3** [comment]
Updated the README with new .env instructions implemented in recent commit and finished up putting in the returned values for routes so that the README can have up-to-date info.

**Comment by DonoghueRyan** [comment]
Last commit was for the .env placement in the README file structure table

**Pull request merged**
